### ISSUE TITLE
Upside down Panel option

### ISSUE THREAD

**Issue by earsneyes** [modulove/A-RYTH-MATHIK#6]
We need additional firmware for the new option to flip the Panel upside down.

display.setRotation(2) right after display init does the trick for the display but there is the need to swap the output & LED pins. For instance… trigger 4 (bottom right) is actually trigger 1 and so on.

Ideally we would finally make the move to github actions building the fw variants.

The firmware uploader should be updated to have another checkbox for upside down config as well.

**Comment by modulove** [comment]
We've added this here:

https://github.com/modulove/A-RYTH-MATIK/pull/9/commits/dcd03e32b35555c4f55d3194ff42b5324ce9e513

Soon to be merged and released once testing is done.
